### ISSUE TITLE
Example for dll

### ISSUE THREAD

**Issue by robertdj** [azurefx/DotNET.jl#5]
Hi

This package looks very interesting! 
Can you provide an example on how to call methods from a DLL? If I have a Class Library with a single file:

```
namespace JuliaTest
{
    public class Foo
    {
        public double Bar(double x)
        {
            return 2 * x;
        }
    }
}
```

How do I call `Bar` from the generated dll? (Please correct me if this is the wrong way to generate the dll :-))

Thanks.

**Comment by azurefx** [comment]
Sure.

```pwsh
PS C:\Users\Azure> Add-Type -Namespace JuliaTest -Name Foo -MemberDefinition @'
>> public double Bar(double x)
>> {
>>     return 2 * x;
>> }
>> '@ -OutputAssembly Example.dll
```

For convenience, I generated the DLL by PowerShell, so the assembly name looks wierd (`di0ato2a.2tx` in this case, and I don't know how to change this...).

```julia
julia> using DotNET

julia> asm=T"System.Reflection.Assembly".LoadFrom("Example.dll")
System.Reflection.RuntimeAssembly("di0ato2a.2tx, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null")
```

The assembly is loaded with `Assembly.LoadFrom` method, just like what we do in C#.

Then we have two ways to reference our `JuliaTest.Foo` class:

```julia
julia> Foo=asm.GetType("JuliaTest.Foo")
JuliaTest.Foo

julia> T"JuliaTest.Foo, di0ato2a.2tx"
JuliaTest.Foo
```

Since `Bar` is not a static method, we need an instance of `Foo`:

```julia
julia> foo=Foo.new()
JuliaTest.Foo("JuliaTest.Foo")

julia> foo.Bar(3.14)
6.28
```

**Comment by robertdj** [comment]
Thanks a lot for your fast reply :-)
